---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../multi-namespace/control-plane2/networking
  - octavia-netattach.yaml

components:
  - ../../../../../va/multi-namespace-skmo/networking-octavia
