---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ci_gen_kustomize_values writes env-specific network-values to the base
# values.yaml before build (see automation vars src_file).
resources:
  - ../../../../multi-namespace/control-plane/networking/nncp

components:
  - ../../../components/octavia-network-values

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia vlan host interface
          name: octavia
          state: up
          type: vlan
          vlan:
            base-iface: _replaced_
            id: _replaced_
  - target:
      kind: NodeNetworkConfigurationPolicy
    patch: |-
      - op: add
        path: /spec/desiredState/interfaces/-
        value:
          description: Octavia bridge
          mtu: 1500
          name: octbr
          type: linux-bridge
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: octavia

replacements:
  - source:
      kind: ConfigMap
      name: octavia-network-values
      fieldPath: data.octavia.base_iface
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.base-iface
  - source:
      kind: ConfigMap
      name: octavia-network-values
      fieldPath: data.octavia.vlan
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
        fieldPaths:
          - spec.desiredState.interfaces.[name=octavia].vlan.id
