---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  - |-
      apiVersion: builtin
      kind: NamespaceTransformer
      metadata:
        name: _ignored_
        namespace: openstack
      setRoleBindingSubjects: none
      unsetOnly: true
      fieldSpecs:
        - path: metadata/name
          kind: Namespace
          create: true

components:
  - ../../../../../../dt/uni04delta/networking/nncp

resources:
  - values.yaml
  - ocp_worker_nodes.yaml

replacements:
  # Static Node IPs: node-3 (worker-0)
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.internalapi_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.tenant_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.ctlplane_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[type=linux-bridge].ipv4.address.0.ip
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.storage_ip
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.ip

  # prefix-length: node-3
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[type=linux-bridge].ipv4.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.internalapi.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=internalapi].ipv4.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.tenant.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=tenant].ipv4.address.0.prefix-length
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.storage.prefix-length
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - spec.desiredState.interfaces.[name=storage].ipv4.address.0.prefix-length

  # Node name and hostname selector
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.node_3.name
    targets:
      - select:
          kind: NodeNetworkConfigurationPolicy
          name: node-3
        fieldPaths:
          - metadata.name
          - spec.nodeSelector.[kubernetes.io/hostname]
