---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../lib/control-plane

patches:
  # Enable heat
  - target:
      kind: OpenStackControlPlane
      name: controlplane
    patch: |-
      - op: replace
        path: /spec/heat/enabled
        value: true
  # Enable telemetry and metricstorage
  - target:
      kind: OpenStackControlPlane
      name: controlplane
    patch: |-
      - op: replace
        path: /spec/telemetry/enabled
        value: true
  - target:
      kind: OpenStackControlPlane
      name: controlplane
    patch: |-
      - op: replace
        path: /spec/telemetry/template/metricStorage/enabled
        value: true

replacements:
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.customServiceConfig
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.glance.default.replicas
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.glance.template.glanceAPIs.default.replicas
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.swift.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.swift.enabled
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.enabled
        options:
          create: true
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.telemetry.metricStorage.enabled
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.telemetry.template.metricStorage.enabled
        options:
          create: true
