---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Octavia bridge on OCP masters is configured by central region NNCP only.
resources:
  - ../../../../multi-namespace/control-plane2/networking/nncp
