# Octavia keys for service-values ConfigMap (shared by central and leaf control planes)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  ovn:
    ovnController:
      nicMappings:
        octavia: octbr
  octavia:
    enabled: true
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    octaviaAPI:
      networkAttachments:
        - internalapi
    octaviaHousekeeping:
      networkAttachments:
        - octavia
    octaviaHealthManager:
      networkAttachments:
        - octavia
    octaviaWorker:
      networkAttachments:
        - octavia
