---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../network-values
  - ../../../../../dt/nova/nova05epsilon/control-plane-post-ceph

resources:
  - values.yaml
  - service-values.yaml
