# This is the kustomization for the FINAL step, edpm-post-ceph
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - network-values
  - ../../../../dt/nova/nova05epsilon/edpm-post-ceph/nodeset

resources:
  - edpm-pre-ceph/nodeset/values.yaml
  - service-values.yaml
  - values.yaml
