---
apiVersion: v1
kind: ConfigMap

metadata:
  name: service-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  preserveJobs: false
  notificationsBus:
    cluster: rabbitmq
  tls:
    caBundleSecretName: ""

  cinderBackup:
    replicas: 0

  designate:
    bind9Services:
      services:
        - metadata:
            annotations:
              metallb.universe.tf/address-pool: designateext
              metallb.universe.tf/allow-shared-ip: designateext
              metallb.universe.tf/LoadBalancerIPs: 172.34.0.80
          spec:
            type: LoadBalancer

  designate-redis:
    enabled: true
    replicas: 1

  octavia:
    amphoraImageContainerImage: quay.io/gthiemonge/octavia-amphora-image
    apacheContainerImage: registry.redhat.io/ubi9/httpd-24:latest
    octaviaAPI:
      networkAttachments:
        - internalapi
    octaviaHousekeeping:
      networkAttachments:
        - octavia
    octaviaHealthManager:
      networkAttachments:
        - octavia
    octaviaWorker:
      networkAttachments:
        - octavia

  ovn:
    ovnController:
      nicMappings:
        datacentre: ospbr
        octavia: octbr

  glance:
    customServiceConfig: |
      [DEFAULT]
      debug = True
      enabled_backends = default_backend:file
      [glance_store]
      default_backend = default_backend
      [default_backend]
      filesystem_store_datadir = /var/lib/glance/images/
    glanceAPIs:
      default:
        replicas: 1
        type: single
